### ISSUE TITLE
Use newline instead of carriage return

### ISSUE THREAD

**Issue by adius** [travishorn/npm-package-store#7]
Does not work on Mac OS X 10.10:

```
$ npmstore
env: node\r: No such file or directory
```

Seems like you've been using carriage return instead of the newline character.

**Comment by AVGP** [comment]
That shouldn't happen anymore. I double checked the file with a hexedit and app.js no longer contains `\r` in the shebang line, so this issue should be fixed.

**Comment by adius** [comment]
Then you should publish it ;-)

**Comment by AVGP** [comment]
Okay, wtf?

Here's the hexdump of the shebang line when the file is downloaded from Github (https://raw.githubusercontent.com/travishorn/npm-package-store/master/app.js):

    23 21 2f 75 73 72 2f 62
    69 6e 2f 65 6e 76 20 6e
    6f 64 65 0a 76

Notice the `0a` in the second last spot? That's `\n`, yay.

However looking at the file that is installed from npm:
    23 21 2f 75 73 72 2f 62 
    69 6e 2f 65 6e 76 20 6e
    6f 64 65 0d 0a

Notice the difference? At the same spot there's `0d` which is `\r` so a DOS line ending!

@travishorn Are you using a windows machine to publish to npm or something?

**Comment by travishorn** [comment]
I am.

**Comment by travishorn** [comment]
I push to GitHub and publish to npm out of the same directory. So it's strange that the file shows up different on each.

**Comment by AVGP** [comment]
Not necessarily, if you use the mingw Git bash, for instance, it by default fixes the line endings (that's how I've got it set up for instance)

And I think (but haven't confirmed yet) that `npm publish` packages up the files locally and uploads them without any changes for line endings

**Comment by travishorn** [comment]
I just opened app.js in Sublime Text (on Windows) and used View > Line Endings > Unix, and saved the file. I pushed to re-published to npm. Not sure if that works or not.

**Comment by AVGP** [comment]
When I'm on a windows computer which I don't trust with line endings, I use https://c9.io where you get a free VM (and IDE) that you can create by cloning a public Github repo for instance... and I publish from there sometimes.
